In [6]:
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = "오늘 날씨는 구름이 많아요."

nouns = komoran.nouns(text)
print(nouns)

dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

nb_classes = len(dics)
targets = list(dics.values())
print(targets)
one = np.eye(nb_classes)

print(one)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[0, 1, 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
from gensim.models import Word2Vec
from konlpy.tag import Komoran
import time

def read_review_data(filename):
    with open(filename, 'r') as f: # 파일열기
        data = [line.split('\t') for line in f.read().splitlines()]
        data= data[1:]
    return data

start = time.time()

print('1 말뭉치 데이터 읽기')
review_data = read_review_data


1


In [8]:
pip install gensim


  Created wheel for smart-open: filename=smart_open-4.2.0-py3-none-any.whl size=109637 sha256=96832b5958550946b46cd1ffaf204f2f303b8bbe26fc94d5618c2c9276d7dc80
  Stored in directory: c:\users\my\appdata\local\pip\cache\wheels\24\f6\ea\70a0761bdfaeacff66662751fe71920e25c4c43d97098a3886
Successfully built smart-open
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.21
    Uninstalling Cython-0.29.21:
      Successfully uninstalled Cython-0.29.21
Note: you may need to restart the kernel to use updated packages.
